./manager.o input/input1.txt output/output1.txt
./manager.o input/input2.txt output/output2.txt
./manager.o input/input3.txt output/output3.txt
./manager.o input/input4.txt output/output4.txt
./manager.o input/input5.txt output/output5.txt
./manager.o input/input6.txt output/output6.txt
./manager.o input/input7.txt output/output7.txt
./manager.o input/input8.txt output/output8.txt
./manager.o input/input9.txt output/output9.txt
./manager.o input/input10.txt output/output10.txt